// Code generated by hand for bootstrap (no controller-gen required). DO NOT EDIT lightly.
package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *SimulationManifest) DeepCopyInto(out *SimulationManifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *SimulationManifest) DeepCopy() *SimulationManifest {
	if in == nil {
		return nil
	}
	out := new(SimulationManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SimulationManifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *SimulationManifestList) DeepCopyInto(out *SimulationManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SimulationManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *SimulationManifestList) DeepCopy() *SimulationManifestList {
	if in == nil {
		return nil
	}
	out := new(SimulationManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SimulationManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for Spec.
func (in *SimulationManifestSpec) DeepCopyInto(out *SimulationManifestSpec) {
	*out = *in
	if in.ThirdParties != nil {
		in, out := &in.ThirdParties, &out.ThirdParties
		*out = make([]ThirdParty, len(*in))
		copy(*out, *in)
	}
	if in.Scenarios != nil {
		in, out := &in.Scenarios, &out.Scenarios
		*out = make([]Scenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto for Status.
func (in *SimulationManifestStatus) DeepCopyInto(out *SimulationManifestStatus) {
	*out = *in
	if in.GeneratedResources != nil {
		in, out := &in.GeneratedResources, &out.GeneratedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for Scenario.
func (in *Scenario) DeepCopyInto(out *Scenario) {
	*out = *in
	if in.Responses != nil {
		in, out := &in.Responses, &out.Responses
		*out = make(map[string][]ScenarioOperationBody, len(*in))
		for k, v := range *in {
			if v == nil {
				(*out)[k] = nil
				continue
			}
			cp := make([]ScenarioOperationBody, len(v))
			copy(cp, v)
			(*out)[k] = cp
		}
	}
}
